version: "3.7"
services:
  streamlit:
    build: ./
    container_name: xinghuo_streamlit
    ports:
      - "9999:9999"
    working_dir: "/workspaces/xinghuo_streamlit"
    volumes:
      - /Volumes/myDriver/github/python3/xinghuo_streamlit:/workspaces/xinghuo_streamlit
    command: "streamlit run main.py --server.port 9999"